# Generated by Django 5.2.5 on 2025-09-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_likes_alter_blog_content_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
